version: "3.9"

services:
  backend:
    build: ./boat
    container_name: boat-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: boat-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
